[package]
name = "tiled-parser"
version = "0.1.0"
edition = "2021"
description = "A simple set of parsers for .tmx and .tsx files created by Tiled"

[dependencies]
roxmltree = "0.19.0"
flate2 = "1.0"
base64 = "0.21"
zstd = "0.13.0"
thiserror = "1.0"
