[package]
name = "tiled-tmx-rs"
version = "0.1.0"
edition = "2021"
description = "Alternate tmx and txs parsers without loading logic"

[dependencies]
roxmltree = "0.19.0"
flate2 = "1.0.28"
base64 = "0.21.7"
zstd = "0.13.0"
thiserror = "1.0.57"
